// These styles apply to every route in the application
import "./globals.css";
import "./Style/css/custom.css";
import "./Style/css/bootstrap.min.css";

export const metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
